# Leave-out-one Cross Validation

### November 2015
### Rohan Fernando, Emre Karaman, Hao Cheng and Dorian Garrick

* Training is based on leaving out observation $j$ from the training data, for $j=1,\ldots, n$ 
* Then, $y_j$ is predicted as $\hat{y}_j = \mathbf{x}_j'\hat{\beta}$, where $\hat{\beta}$ is the estimate of $\beta$ estimated from the data set where observation $j$ was left out. 
* Thus, cross validation by straightforward application of this approach, would require $n$ analyses with $n-1$ observations in each analysis. 
* Fortunately, when the marker effects model (MEM) is used, leave-one-out cross validation can be performed with little more effort than is required for a single analysis with $n$ observations by using a well-known strategy used in least-squares regression to compute the predicted residual sum of squares (PRESS) statistic. 
* When $k>n$ the breeding value model (BVM) is more efficient because for this model the mixed model equations are of order $n\times n$. 
* We show below how leave-one-out cross validation can also be performed using either or the MEM and BVM with little more effort than is required for a single analysis with $n$ observations. Dan Gianola is also working on this problem, even for the Bayesian alphabet methods.

## Marker Effects Model
Use of the MEM is more efficient when $n>k$ because for this model the mixed model equations are of order $k\times k$. The MEM for G-BLUP can be written as

$$
        \mathbf{y}=\mathbf{X}\mathbf{\beta}+\mathbf{e},
$$

where $\mathbf{y}$ has been corrected for all effects other than $\mathbf{\beta}$, the marker effects, and $\mathbf{X}$ is the matrix of marker covariates. Often it is assumed that marker effects are identically and independetly distributed (iid) random variables with null means and variances $\sigma^2_\beta$. Thus, under the usual assumption that the resudual are iid with null means and variances $\sigma^2_e$, $\text{E}(\mathbf{y}) = \mathbf{0}$.

Then, BLP of $\beta$
can be obtained by solving the $k\times k$ mixed model equations

$$
\left(\mathbf{X'X}+\mathbf{I}\lambda\right)\hat{\mathbf{\beta}}=\mathbf{X'y},
$$
where $\lambda=\frac{\sigma_{e}^{2}}{\sigma_{\beta}^{2}}$.

Now, BLUP for $\mathbf{\beta_{-j}}$, where observation $j$ is
left out, can be obtained as

$$
\mathbf{\hat{\beta}}_{-j}=
\left(\mathbf{X}_{-j}'\mathbf{X}_{-j}+\mathbf{I}\lambda\right)^{-1}\mathbf{X}_{-j}'
    \mathbf{y}_{-j},\label{eq:PRESS1-1} \tag{1}
$$

where $\mathbf{X}_{-j}$ is $\mathbf{X}$ with the $j$th
row removed and $\mathbf{y}_{-j}$ is $\mathbf{y}$ with the
$j$th element removed.

But, from the matrix inverse lemma,

$$
\begin{align}
\left(\mathbf{X}_{-j}'\mathbf{X}_{-j}+\mathbf{I}\lambda\right)^{-1} & =\left(\mathbf{X}'\mathbf{X}+\mathbf{I}\lambda-\mathbf{x}_{j}\mathbf{x}_{j}^{'}\right)^{-1}\nonumber \\
 & =\left(\mathbf{X}'\mathbf{X}+\mathbf{I}\lambda\right)^{-1}-\frac{\left(\mathbf{X}'\mathbf{X}+\mathbf{I}\lambda\right)^{-1}\mathbf{x}_{j}\mathbf{x}_{j}^{'}\left(\mathbf{X}'\mathbf{X}+\mathbf{I}\lambda\right)^{-1}}{1-H_{jj}},\label{eq:PRESS2-1} \tag{2}
\end{align} 
$$

where the quadratic $H_{jj}=\mathbf{x}_{j}^{'}\left(\mathbf{X}'\mathbf{X}+\mathbf{I}\lambda\right)^{-1}\mathbf{x}_{j}$
is the $j$th diagonal element of $\mathbf{H}=\mathbf{X}\left(\mathbf{X}'\mathbf{X}+\mathbf{I}\lambda\right)^{-1}\mathbf{X}^{'}$.

Using (\ref{eq:PRESS2-1}) in (\ref{eq:PRESS1-1}), the prediction
residual for the $j$th observation can be written as 

$$
\begin{align*}
\hat{e_{j}} & =y_{j}-\mathbf{x}_{j}^{'}\hat{\mathbf{\beta}}_{-j}\\
 & =y_{j}-\mathbf{x}_{j}^{'}\left[\left(\mathbf{X}'\mathbf{X}+\mathbf{I}\lambda\right)^{-1}-\frac{\left(\mathbf{X}'\mathbf{X}+\mathbf{I}\lambda\right)^{-1}\mathbf{x}_{j}\mathbf{x}_{j}^{'}\left(\mathbf{X}'\mathbf{X}+\mathbf{I}\lambda\right)^{-1}}{1-H_{jj}}\right]\mathbf{X}_{-j}'\mathbf{y}_{-j}\\
 & =\frac{y_{j}-\mathbf{x}_{j}^{'}\hat{\mathbf{\beta}}}{1-H_{jj}}.
\end{align*}
$$

Then PRESS is calculated as $\sum_{j=1}^{n}\hat{e_{j}}^{2}$. 
The accuracy
of genomic prediction is often quantified as the correlation between
the predicted and observed values of $y_{j}$, and this correlation
can be estimated from the values of $\hat{y}_{j}$ efficiently computed
as $\hat{y}_{j}=y_{j}-\hat{e}_{j}$ and the observed values of $y_{j}.$

## Breeding Value Model

When $n < k$, $\mathbf{x}_{j}'\hat{\mathbf{\beta}}$ can be obtained more efficiently by solving the mixed model equations (MME) for the BVM: 
$$
\begin{align*}
\mathbf{y} & =\mathbf{Zu}+\mathbf{e},
\end{align*}
$$

where $\mathbf{u}=\mathbf{X}\mathbf{\beta}$,  $\text{Var}\left(\mathbf{u}\right)=\mathbf{XX'}\sigma_{\beta}^{2}$, and $\mathbf{Z}$ is the identity matrix of order $k$. As in the MEM, in this model also $\text{E}(\mathbf{y}) = \mathbf{0}$, and in both models $\text{Var}(\mathbf{y}) = \mathbf{X}\mathbf{X}'\sigma_{\beta}^{2}+\mathbf{I}\sigma_{e}^{2}$. Thus, these two models are said to be equivalent, and yield identical pedictions.

The MME for this model are:

$$
\left(\mathbf{Z'Z}+\mathbf{G}^{-1}\lambda\right)\hat{\mathbf{u}}=\mathbf{Z'y},
$$

where $\mathbf{G} = \mathbf{XX'}$. So, because of the equivalence of these two models, when $n < k$, $\mathbf{x}_{j}'\hat{\mathbf{\beta}}$ is more efficiently obtained as $\hat{u}_j$. Similarly, 
$\text{Var}(\mathbf{x}_{j}'\mathbf{\beta} - \mathbf{x}_{j}'\hat{\mathbf{\beta}}) = 
\mathbf{x}_{j}'\left(\mathbf{X}'\mathbf{X}+\mathbf{I}\lambda\right)^{-1}\mathbf{x}_{j}\sigma_{e}^{2}$ can be obtained more efficiently as 
$\text{Var}(u_j - \hat{u}_j) = 
\mathbf{z}_{j}'\left(\mathbf{Z'Z}+\mathbf{G}^{-1}\lambda\right)^{-1}\mathbf{z}_{j}\sigma_{e}^{2}$. Using these two equivalent results, the formula for $\hat{e}_j$ becomes:

$$
\begin{align*}
\hat{e_{j}} & =y_{j}-\mathbf{x}_{j}^{'}\hat{\mathbf{\beta}}_{-j}\\
 & =\frac{y_{j}-\mathbf{x}_{j}^{'}\hat{\mathbf{\beta}}}{1-H_{jj}}\\
 & =\frac{y_{j}-\mathbf{x}_{j}^{'}\hat{\mathbf{\beta}}}{1-\mathbf{x}_{j}'\left(\mathbf{X}'\mathbf{X}+\mathbf{I}\lambda\right)^{-1}\mathbf{x}_{j}}\\
 & =\frac{y_{j} - \hat{u}_j}
 {1-\mathbf{z}_{j}'\left(\mathbf{Z}'\mathbf{Z}+\mathbf{G}^{-1}\lambda\right)^{-1}\mathbf{z}_{j}}\\
\end{align*}
$$

Here, $\mathbf{Z}$ is the identity matrix, and so 
$\mathbf{z}_{j}'\left(\mathbf{Z}'\mathbf{Z}+\mathbf{G}^{-1}\lambda\right)^{-1}\mathbf{z}_{j}$ becomes $c^{j,j}$, 
the $j$th diagonal of the inverse of $\mathbf{C} = \left(\mathbf{Z}'\mathbf{Z}+\mathbf{G}^{-1}\lambda\right)$.  Then,

$$
\begin{align*}
\hat{e_{j}} &  =\frac{y_{j} - \hat{u}_j}
 {1-c^{j,j}}.
\end{align*}
$$

## Numerical Example

In [1]:
using Distributions
function simDat(nObs,nLoci,bMean,bStd,resStd)
    X = sample([0;1;2],(nObs,nLoci))
    b = rand(Normal(bMean,bStd),size(X,2))
    y = X*b + rand(Normal(0.0, resStd),nObs)
    return (y,X,b)
end

simDat (generic function with 1 method)

In [2]:
srand(31415) # seed for random number generator
vara = 50
vare = 200
nObs,nLoci,bMean,bStd,resStd = 5,10,0.0,sqrt(vara),sqrt(vare)
res = simDat(nObs,nLoci,bMean,bStd,resStd);

In [3]:
y = res[1]
X = res[2]

5x10 Array{Int64,2}:
 2  0  2  0  0  1  0  0  0  2
 2  0  0  2  1  1  1  1  0  1
 0  0  1  0  1  0  0  0  1  0
 2  1  0  2  2  1  0  0  1  0
 2  2  2  1  0  2  0  0  0  1

### Inefficient Approach

In [4]:
function LOjEHat(X,y,vara,vare,j)
    λ = vare/vara
    n = size(X,1)
    k = size(X,2)
    xPj = X[j,:]
    yj  = y[j]
    sel = fill(true,n)
    sel[j] = false
    X = X[sel,:]
    y = y[sel]
    betaHat = inv(X'X + eye(k)*λ)*X'y
    return yj - xPj*betaHat
end

LOjEHat (generic function with 1 method)

In [5]:
eHatN = [LOjEHat(X,y,vara,vare,j) for j=1:nObs];
eHatN

5-element Array{Any,1}:
 [-27.273554798523264]
 [-10.482056545905907]
 [-9.263847750012747] 
 [-3.881854751591085] 
 [57.63494553766701]  

In [6]:
eHatN'eHatN

1-element Array{Float64,1}:
 4276.39

## Efficient Approach

### Results from HMME for MEM

In [7]:
λ = vare/vara
H = X*inv(X'X + eye(nLoci)*λ)*X'

5x5 Array{Float64,2}:
  0.587565    0.101121    0.074395   -0.0720657   0.209591 
  0.101121    0.571702   -0.0688731   0.217864    0.0272882
  0.074395   -0.0688731   0.366327    0.126923   -0.0124895
 -0.0720657   0.217864    0.126923    0.598508    0.12114  
  0.209591    0.0272882  -0.0124895   0.12114     0.638768 

In [8]:
d = 1 - diag(H)
eHatMEM = (y - H*y) ./ d 

5-element Array{Float64,1}:
 -27.2736 
 -10.4821 
  -9.26385
  -3.88185
  57.6349 

In [9]:
eHatMEM'eHatMEM

1-element Array{Float64,1}:
 4276.39

### Accuracy of prediction: cor($y$,$\hat{y}$)

In [10]:
yHat = y - eHatMEM

5-element Array{Float64,1}:
 29.1861 
 12.8075 
  1.48517
 17.7184 
  6.19443

In [11]:
cor(y,yHat)

-0.2326421820030729

### Same Results from HMME for BVM

In [12]:
Z    = eye(5)
Gi   = inv(X*X')

5x5 Array{Float64,2}:
  0.372072  -0.23288   -0.27147    0.267901  -0.250279
 -0.23288    0.390364   0.292215  -0.347535   0.120678
 -0.27147    0.292215   0.675887  -0.368726   0.164622
  0.267901  -0.347535  -0.368726   0.447691  -0.212581
 -0.250279   0.120678   0.164622  -0.212581   0.261878

In [13]:
Lhs = Z'Z + Gi*λ
Rhs = Z'y
iLhs = inv(Lhs)

5x5 Array{Float64,2}:
  0.587565    0.101121    0.074395   -0.0720657   0.209591 
  0.101121    0.571702   -0.0688731   0.217864    0.0272882
  0.074395   -0.0688731   0.366327    0.126923   -0.0124895
 -0.0720657   0.217864    0.126923    0.598508    0.12114  
  0.209591    0.0272882  -0.0124895   0.12114     0.638768 

In [14]:
sol  = iLhs*Rhs

5-element Array{Float64,1}:
 13.1611 
  6.81487
 -1.90843
 15.3951 
 43.0098 

In [15]:
d = 1 - diag(Z*iLhs*Z')

5-element Array{Float64,1}:
 0.412435
 0.428298
 0.633673
 0.401492
 0.361232

In [16]:
eHatBVM = (y - Z*sol)./d 

5-element Array{Float64,1}:
 -27.2736 
 -10.4821 
  -9.26385
  -3.88185
  57.6349 

### Accuracy of prediction: cor($y$,$\hat{y}$)

In [17]:
yHat = y - eHatBVM

5-element Array{Float64,1}:
 29.1861 
 12.8075 
  1.48517
 17.7184 
  6.19443

In [18]:
cor(y,yHat)

-0.23264218200307246

In [19]:
[eHatMEM  eHatBVM]

5x2 Array{Float64,2}:
 -27.2736   -27.2736 
 -10.4821   -10.4821 
  -9.26385   -9.26385
  -3.88185   -3.88185
  57.6349    57.6349 

### MCMC Approach

In [20]:
function Gibbs(A,x,b)
    n = size(x,1)
    for i=1:n
        cVar = 1.0/A[i,i]
        cMean   = cVar*(b[i] - A[:,i]'x)[1] + x[i]
        x[i]    = randn()*sqrt(cVar*vare) + cMean 
    end
end

Gibbs (generic function with 1 method)

In [21]:
nIter = 1000000
k = size(Lhs,1)
b = zeros(k)
ss = zeros(nIter,k)
for i =1:nIter
    Gibbs(Lhs,b,Rhs)
    ss[i,:] = b'
end

In [22]:
bMCMC = mean(ss,1)'

5x1 Array{Float64,2}:
 13.1799 
  6.80966
 -1.89962
 15.3909 
 43.0179 

In [23]:
dMCMC = 1 - var(ss,1)'/vare

5x1 Array{Float64,2}:
 0.412045
 0.426936
 0.633042
 0.402129
 0.36139 

In [24]:
eHatMCMC = (y - Z*bMCMC)./ d 

5x1 Array{Float64,2}:
 -27.319  
 -10.4699 
  -9.27776
  -3.87131
  57.6123 

### Comparison of Results from MEM, BVM, BVM-MCMC

In [25]:
[eHatMEM  eHatBVM eHatMCMC]

5x3 Array{Float64,2}:
 -27.2736   -27.2736   -27.319  
 -10.4821   -10.4821   -10.4699 
  -9.26385   -9.26385   -9.27776
  -3.88185   -3.88185   -3.87131
  57.6349    57.6349    57.6123 

In [26]:
[eHatMEM'eHatMEM eHatBVM'eHatBVM eHatMCMC'eHatMCMC]

1x3 Array{Float64,2}:
 4276.39  4276.39  4276.19

### Breeding value model with $n$=1000 and $k$=50,000
#### Model

$$
        \mathbf{y}=\mathbf{X}\mathbf{\beta} + \mathbf{Zu} + \mathbf{e},
$$

where $\mathbf{u} = \mathbf{M\alpha}$, $\mathbf{M}$ is the matrix of marker covariates and $\mathbf{\alpha}$ are the marker effects.

In [30]:
using Distributions
using Gadfly
function simDat(nObs,nLoci,bMean,bStd,resStd)
    X=[ones(nObs,1) sample([0.0,1.0,2.0],(nObs,nLoci))]
    b=[100.0; rand(Normal(bMean,bStd),nLoci)]
    y=X*b+rand(Normal(0.0,resStd),nObs)
return(y,X,b)

end

simDat (generic function with 1 method)

In [34]:
srand(1234)
nObs   = 1000;
nLoci  = 50000;
bMean  = 0.0;
bStd   = sqrt(1.0/(nLoci*0.5))
resStd = 1.0
res    = simDat(nObs,nLoci,bMean,bStd,resStd)
vare   = resStd^2
varb   = bStd^2
y = res[1]
X = res[2]
b = res[3]
M = X[:,2:end]
X = X[:,1]
λ = vare/varb

Gi   = inv(M*M')
Z    = eye(nObs);
Lhs  = [X'X X'Z
        Z'X (Z'Z+Gi*λ)]
Rhs  =  [X'y 
        Z'y]
iLhs = inv(Lhs);
W    = [X Z]
sol  = iLhs*Rhs
d    = 1 - diag(W*iLhs*W')
eHatBVM = (y - W*sol)./d 
yHat    = y - eHatBVM
cor(y,yHat)

0.14878684486281213

In [35]:
cor(y,W*sol)

0.9981111316697726

In [36]:
yHat[1]

100.61705265784505

#### Exercise
1. Compute $\hat{y}_1$ by training with a dataset leaves out $y_1$. Compare result with that obtained above.
2. Why is the accuracy so low?